# Spring Boot Application Configuration
server.port=8080
spring.application.name=openapi-demo
dingtalk.clientId=dingus9mlh3dc0bqoeir
dingtalk.clientSecret=6GrhTw8YA03OK2Wp-vnfffqvw5zxeLkE2-u3QONrLDHIBbTFI40eHak9f-YUjg1W
# Character encoding configuration
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Sangfor API Configuration
sangfor.console.address=https://117.133.161.226:4433
sangfor.api.id=1207623
sangfor.api.secret=c9b3d2e52f844dad99dc0eeddb7384e6

