# Spring Boot Application Configuration
server.port=8080
spring.application.name=openapi-demo
dingtalk.clientId=dingus9mlh3dc0bqoeir
dingtalk.clientSecret=6GrhTw8YA03OK2Wp-vnfffqvw5zxeLkE2-u3QONrLDHIBbTFI40eHak9f-YUjg1W
# Character encoding configuration
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

